services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - 8200:8000