services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.20
    ports:
      - "8200:8000"