###
GET http://localhost:8080/ai/chat?question=Hello

### Tell me a joke about {subject}
GET http://localhost:8080/ai/chat-with-prompt?subject=Tollywood

### Tell me a joke about {subject}
GET http://localhost:8080/ai/chat-with-system-prompt?subject=Tollywood

### What are the best movies directed by {director}?
GET http://localhost:8080/ai/chat/movies?director=Tarantino

### What are the best movies directed by {director}?
GET http://localhost:8080/ai/chat/movies-as-map?director=Tarantino

### What are the best movies directed by {director}?
GET http://localhost:8080/ai/chat/movies-as-list?director=Tarantino

###
GET http://localhost:8080/ai/rag/people?name=Siva
